# Generated by Django 4.2.2 on 2023-06-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mailing_alter_client_options_alter_client_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='clients',
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='main.client'),
        ),
    ]
