# Generated by Django 4.2.2 on 2023-06-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_mailing_clients_mailing_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'verbose_name': 'Лог рассылки', 'verbose_name_plural': 'Лог рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('running', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, verbose_name='Статус'),
        ),
    ]
