# Generated by Django 4.2.2 on 2023-07-04 09:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_client_client_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='send_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отправки'),
        ),
    ]
